apka/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('pokoj.urls', namespace='pokoj')),
    url(r'^pokoj/', include('pokoj.urls', namespace='pokoj')),
    url(r'^konta/', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
]

pokoj/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from .models import Ogloszenia

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^lista/', login_required(ListView.as_view(model=Ogloszenia)), name='lista'),
    url(r'^dodaj/$', views.OgloszenieCreate.as_view(), name='dodaj'),
    url(r'^edytuj/(?P<pk>\d+)/', views.OgloszenieUpdate.as_view(), name='edytuj'),
    url(r'^usun/(?P<pk>\d+)/', views.OgloszenieDelete.as_view(), name='usun'),
    url(r'^info/(?P<pk>\d+)/', views.OgloszenieDetailView.as_view(), name='info'),
]

pokoj/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User

class Ogloszenia(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    tytul = models.CharField(verbose_name='Tytuł', max_length=30)
    opis = models.TextField(blank=False, help_text='Opis Ogłoszenia')
    data = models.DateField('dodano', auto_now_add=True)

    def __unicode__(self):
        return u'%s' % (self.tytul)

    class Meta:
        verbose_name = "ogłoszenie"
        verbose_name_plural = 'ogłoszenia'

pokoj/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm, Textarea
from . import models
from django.forms.models import inlineformset_factory


class OgloszeniaForm(ModelForm):

    class Meta:
        model = models.Ogloszenia
        exclude = ('data', 'autor')
        widgets = {'opis': Textarea(attrs={'rows': 2, 'cols': 80})}

pokoj/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from . import models
from . import forms
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django.views.generic import DetailView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect

def index(request):
    """Strona główna"""
    kontekst = {'komunikat': 'Witaj w aplikacji Pokoj Nauczycielski!'}
    return render(request, 'pokoj/index.html', kontekst)
  
@method_decorator(login_required, 'dispatch')
class OgloszenieCreate(CreateView):
    model = models.Ogloszenia
    form_class = forms.OgloszeniaForm
    success_url = reverse_lazy('pokoj:lista')  # '/pokoj/lista'
    
    def get_context_data(self, **kwargs):
        context = super(OgloszenieCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['ogloszenia'] = forms.OgloszeniaForm(self.request.POST)
        else:
            context['ogloszenia'] = forms.OgloszeniaForm()
        return context
      
    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.autor = self.request.user
        self.object = form.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        return self.render_to_response(
            self.get_context_data(form=form)
        )
      
@method_decorator(login_required, 'dispatch')
class OgloszenieUpdate(UpdateView):
    """Widok aktualizuacji"""

    model = models.Ogloszenia
    form_class = forms.OgloszeniaForm
    success_url = reverse_lazy('pokoj:lista')  # '/pizza/lista'

    def get_context_data(self, **kwargs):
        context = super(OgloszenieUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['ogloszenia'] = forms.OgloszeniaForm(
                self.request.POST,
                instance=self.object)
        else:
            context['ogloszenia'] = forms.OgloszeniaForm(instance=self.object)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.autor = self.request.user
        self.object = form.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        return self.render_to_response(
            self.get_context_data(form=form)
        )

@method_decorator(login_required, 'dispatch')
class OgloszenieDelete(DeleteView):
    model = models.Ogloszenia
    success_url = reverse_lazy('pokoj:lista')  # '/pizza/lista'

    def get_context_data(self, **kwargs):
        context = super(OgloszenieDelete, self).get_context_data(**kwargs)
        return context
      
@method_decorator(login_required, 'dispatch')
class OgloszenieDetailView(DetailView):
    model = models.Ogloszenia

    def get_context_data(self, **kwargs):
        context = super(OgloszenieDetailView, self).get_context_data(**kwargs)
        return context

pokoj/templates/pokoj/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{% block tytul_head %}Pokój nauczycielski{% endblock %}</title>

  <!-- Latest compiled and minified CSS 
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  -->  
  <link href="{% static 'pokoj/css/bootstrap.min.css' %}" rel="stylesheet" >
  <link href="{% static 'pokoj/css/pokoj.css' %}" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="http://csshake.surge.sh/csshake.min.css">
</head>
<body>

<!-- Nawigacja -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Przełącz nawigację</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'pokoj:index' %}">
        <img src="{% static 'pokoj/images/logo.jpg' %}" class="img-thumbnail">
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        {% if not user.is_authenticated %}
        <li><a href="{% url 'auth_login' %}">Zaloguj</a></li>
        <li><a href="{% url 'registration_register' %}">Utwórz konto</a></li>
        {% else %}
        <li><a>Zalogowany jako {{ user.username }}</a></li>
        <li><a href="{% url 'pokoj:lista' %}">Lista ogłoszeń</a></li>
        <li><a href="{% url 'auth_logout' %}">Wyloguj [ {{ user.username }} ]</a></li>
        {% endif %}
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<!-- Treść główna -->
<div class="container">

  <div class="row">

    <div class="col-sm-9">

      <noscript><p>Uaktywnij bsługę JavaScript.</p></noscript>

      <!-- blok tytułu strony -->
      <h1>{% block tytul_h1 %}{% endblock %}</h1>

      <!-- blok treści -->
      <div class="tresc">
        {% block tresc %}{% endblock %}
      </div>

    </div>

    <div class="col-sm-3">
      <div class="well">
        <h4>Przydatne linki</h4>
        <ul>
          {% block linki_ul %}
            <li><a href="http://soswlublin.pl">SOSWLublin - strona szkoły</a></li>
            <li><a href="http://soswinformatyka.pl/">SOSWInformatyka</a></li>
          {% endblock %}
        </ul>
      </div> <!--/well-->
    </div>

  </div> <!--/row -->
</div> <!--/container -->
<div class="container footer">
  <footer style="margin-top: 35%;">
    <div class="row">
      <div class="col-sm-12 text-center">
        <div class="well">
          Pokój nauczycielski<br>&copy; by Kamil Karpiński 2017 <br /><br />
          Projekt zrealizowany przez ucznia Kamila Karpińskiego w ramach ogólnopolskiej akcji "Koduj z klasą" we współpracy z Centrum Edukacji Obywatelskiej.<br />
          <a href="https://kodujzklasa.ceo.org.pl/" target="_blank"><img class="shake-slow" src="https://kodujzklasa.ceo.org.pl/sites/kodujzklasa.ceo.org.pl/themes/eduglob/logo.png" /></a>
          <a href="https://soswinformatyka.pl" target="_blank"><img class="shake-slow" src="http://soswinformatyka.pl/assets/img/logo.png" /></a><br />
          <a href="https://soswlublin.pl/wyscigowa" target="_blank"><img class="shake-slow" src="http://soswlublin.pl/wyscigowa/templates/september-2012/images/header.png" /></a>
        </div>
      </div>
    </div>
  </footer>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

pokoj/templates/pokoj/index.html
{% extends "pokoj/base.html" %}

{% block tytul_h1 %}
  Pokój nauczycielski
{% endblock %}

{% block tresc %}
  <p>{{ komunikat }}</p>
  Pokój nauczycielski jest to aplikacja służąca usprawnieniu dystrybucji ogłoszeń w szkole. <br />
Jest dostępna online po zalogowaniu i weryfikacji użytkownika tylko dla nauczycieli SOSW w Lublinie. <br />
Oparta jest o język Python z użyciem frameworka Django oraz języków programowania: HTML, CSS, JavaScript. <br />
Serdecznie zapraszamy do korzystania!
{% endblock %}

<ul>
  {% if not user.is_authenticated %}
    <li><a href="{% url 'auth_login' %}" class="btn btn-primary">Zaloguj się</a></li>
    <li><a href="{% url 'registration_register' %}" class="btn btn-primary">Utwórz konto</a></li>
  {% else %}
    <li><a href="{% url 'auth_logout' %}" class="btn btn-danger">Wyloguj się</a></li>
  {% endif %}
</ul>

pokoj/templates/pokoj/ogloszenia_confirm_delete.html
{% extends "pokoj/base.html" %}
{% block tresc %}
<h1>Usuwanie ogłoszenia</h1>
<form action="." method="post">
  {% csrf_token %}
  <p>Czy na pewno chcesz usunąć ogłoszenie?</p>
    </ol>
  <button type="submit" class="btn btn-danger">Tak</button>
  <a href="{% url 'pokoj:lista' %}" class="btn btn-default">Nie</a>
</form>
{% endblock %}

pokoj/templates/pokoj/ogloszenia_detail.html
{% extends "pokoj/base.html" %}
{% block tresc %}
<h1>Szczegóły ogłoszenia</h1>
<table class="table table-hover table-bordered">
  <tr><td>Tytuł:</td><td>{{ object.tytul }}</td></tr>
  <tr><td>Opis:</td><td>{{ object.opis }}</td></tr>
  <tr><td>Dodano:</td><td>{{ object.data }}</td></tr>
  <tr><td>Autor:</td><td>{{ object.autor }}</td></tr>
</table>

<a href="{% url 'pokoj:lista' %}" class="btn btn-default">Wróć do listy</a>
{% endblock %}

pokoj/templates/pokoj/ogloszenia_form.html
{% extends "pokoj/base.html" %}
{% block tresc %}
<h1>Dodaj/Edytuj ogłoszenie</h1>
<form action="." method="post" id="pform">
  {% csrf_token %}
  {{ form.as_p }}

  <br /><input type="submit" class="btn btn-success" value="Zapisz">
  <a href="{% url 'pokoj:lista' %}" class="btn btn-default">Anuluj</a>
</form>

{% endblock %}

pokoj/templates/pokoj/ogloszenia_list.html
{% extends "pokoj/base.html" %}

{% block tytul_h1 %}
  Lista ogłoszeń
{% endblock %}

{% block tresc %}
<a href="{% url 'pokoj:dodaj' %}" class="btn btn-success pull-right">Dodaj nowe ogłoszenie</a><br /><br />
<table class="table table-hover table-bordered">
<thead>
	<tr><th>Lp.</th><th>Tytuł ogłoszenia</th><th>Opis</th><th>Data dodania</th><th colspan="3">Operacje</th></tr>
</thead>
<tbody>
	{% for p in object_list %}
	<tr>
		<td>{{ forloop.counter }}</td>
		<td>{{ p.tytul }}</td>
		<td>{{ p.opis }}</td>
		<td>Dodane przez {{ p.autor.username }} dnia {{ p.data }}</td>
		<td>
        <a href="{% url 'pokoj:info' p.id %}" class="btn btn-default">Szczegóły</a>
        {% if p.autor.username == user.username %}
		</td>
		<td>
				<a href="{% url 'pokoj:edytuj' p.id %}" class="btn btn-primary">Edytuj</a>
		</td>
		<td>
				<a href="{% url 'pokoj:usun' p.id %}" class="btn btn-danger">Usuń</a>
		</td>
        {% endif %}
		</td>
	</tr>
	{% endfor %}
</tbody>
</table>
{% endblock %}